properties([parameters([string(defaultValue: '2019', description: '', name: 'date', trim: false)]), pipelineTriggers([cron('0 8 * * 1')])])

node('master') {
    stage('Provision') {                
        echo 'PIPELINE STARTED'
        // Will run on the slave with name or tag specialSlave
        sh 'echo /etc/os-release'
    }
    stage ('Starting ART job') {
        build job: 'second'//, parameters: [ string(name: 'param1', value:'test_param'), string(name:'dummy', value: "${index}")]
    }
}


