Vagrant.configure("2") do |config|

  ## LINUX VMS

  config.vm.define "ubuntu01" do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.hostname = "project-x"
    config.vm.network "private_network", ip: "172.16.1.10"
    config.vm.provision :shell, path: "bootstrap.sh"
    config.vm.provider "virtualbox" do |hv|
      hv.memory = 2048
    end
  end
end
