properties([pipelineTriggers([cron('0 8 * * 1')])])
import java.text.SimpleDateFormat

node {
    stage('Set date') {
        def weekdayName = new SimpleDateFormat("E") // the day of the week abbreviated
        def yearWeek = new SimpleDateFormat("yyyy/w") // year/week
        
        def today = new Date()
        def previousDate = today - 7

        def weekday = (weekdayName.format(today))
        
        if(weekday == 'Mon') { 
            echo "Today is ${weekday}" 
            currentDate = (yearWeek.format(previousDate)) // Previous week yyyy/w
        } else{ 
            currentDate = (yearWeek.format(today))
            echo 'Today is not Monday'
        }
        echo currentDate
    }
    stage ('Start second job') {
        build (job: "second", parameters: [
        [
            $class: 'StringParameterValue',
            name: 'PARAM',
            value: "${currentDate}"
        ],
    ],
    wait: true)
    }
}
