properties([pipelineTriggers([cron('0 8 * * 1')])])
import java.text.SimpleDateFormat

node {
    stage('Set date') {
        def weekday = new SimpleDateFormat("E") // the day of the week abbreviated
        def yearWeek = new SimpleDateFormat("yyyy/w")

        def now = new Date()
        def previousDate = now.previous()
        def date = (weekday.format(now))

        if(date == 'Mon') {
            echo "Today is ${date}"
            currentDate = (yearWeek.format(previousDate)) // Previous week yyyy/w
        } else{
            currentDate = (yearWeek.format(now))
            echo 'Today is not Monday'
        }
        echo currentDate
    }
    stage ('Start second job') {
        build (job: "second", parameters: [
        [
            $class: 'StringParameterValue',
            name: 'PARAM',
            value: "${currentDate}"
        ],
    ],
    wait: true)
    }
}
