properties([parameters([string(defaultValue: '', description: '', name: 'PARAM', trim: false)])])

node('nodejs') {
    stage('pull scm') {
        //git poll: true, url: 'https://github.com/fnikolov/project-y/'
    }

    stage('run app') {
        sh "nodejs app.js"
    }
}
